CREATE TABLE IF NOT EXISTS `#__arcna_animals` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `catid` int(11) unsigned NOT NULL DEFAULT '0',
  `title` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) NOT NULL DEFAULT '',
  `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` int(11) unsigned NOT NULL DEFAULT '0',
  `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` int(11) unsigned NOT NULL DEFAULT '0',
  `checked_out` int(11) unsigned NOT NULL DEFAULT '0',
  `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `published` tinyint(3) NOT NULL DEFAULT '0',
  `ordering` int(11) NOT NULL DEFAULT '0',
  `introtext` mediumtext NOT NULL,
  `fulltext` mediumtext NOT NULL,
  `params` text NOT NULL,
  `metakey` text NOT NULL,
  `metadesc` text NOT NULL,
  `metadata` text NOT NULL,
  `access` int(11) unsigned NOT NULL DEFAULT '0',
  `hits` int(11) unsigned NOT NULL DEFAULT '0',
  `image` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `species` varchar(255) NOT NULL,
  `breed` varchar(255) NOT NULL,
  `age` varchar(255) NOT NULL,
  `gender` varchar(255) NOT NULL,
  `color` varchar(255) NOT NULL,
  `altered` varchar(255) NOT NULL,
  `location_state` varchar(255) NOT NULL,
  `location_city` varchar(255) NOT NULL,
  `shelter_name` varchar(255) NOT NULL,
  `shelter_id` varchar(255) NOT NULL,
  `shelter_phone` varchar(255) NOT NULL,
  `shelter_address` varchar(255) NOT NULL,
  `real_time_need` varchar(255) NOT NULL,
  `real_time_status` varchar(255) NOT NULL,
  `adoption_status` varchar(255) NOT NULL,
  `date_in` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `available_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `pull_by_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `contact_name` varchar(255) NOT NULL,
  `contact_email` varchar(255) NOT NULL,
  `contact_phone` varchar(255) NOT NULL,
  `comments` text NOT NULL,
  `special_needs` text NOT NULL,
  `behavior_evaluation` text NOT NULL,
  `concerns` text NOT NULL,
  `general_comments` text NOT NULL,
  
  PRIMARY KEY (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`published`),
  KEY `idx_catid` (`catid`),
  KEY `idx_createdby` (`created_by`)
) AUTO_INCREMENT=0 ;
